# Generated by Django 5.1.3 on 2024-11-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=30)),
                ('posted', models.BooleanField(default=False)),
            ],
        ),
    ]
